[package]
name = "demo-leptos"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6.11", features = ["csr", "nightly"] }
gloo-console = "0.3.0"
gloo-utils = "0.2.0"
hashbrown = "0.14.3"
wasm-bindgen = "0.2.92"
webtric = { path="..", features=["leptos"] }